# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Mauricio Freitas
# Description of the Site
description: Olá, seja bem-vindo.
# URL of Image of the Site
site-image: 
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: https://user-images.githubusercontent.com/66425036/209043786-e1bd859f-85f5-4955-9e13-d25cd8d0f215.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://user-images.githubusercontent.com/66425036/209040588-5fa1ebc1-86c4-4c0e-95c5-cf3b289b8e50.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: mauriciop108@gmail.com
facebook_username: 
twitter_username: HtMau
instagram_username: omauriciofreitas
linkedin_username: mauricio-hastenreiter-94754014a
github_username: MauFreitas
youtube_channel_id: UCMjVmSMial8750qZCLCOoqQ
reddit_username: iLendaBr
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: /

# Name of the Author
author-name: Freitas,Mauricio
# URL for the Image of the Author
author-image: https://user-images.githubusercontent.com/66425036/209040510-471d738d-ce26-4513-a8f7-796ef5243e7a.jpg
# 60 Words About the Author
author-about: Sou um jovem desenvolvedor de jogos e recém-formado em tecnologia de jogos, estou ansioso para começar minha carreira na indústria. Com habilidades em programação,
 design de jogos e arte, estou pronto para colocar minhas habilidades em prática e contribuir para o desenvolvimento de jogos incríveis. Sou apaixonados por jogos e 
 sempre estão buscando novas formas de melhorar minhas habilidades. Apesar de ser novo no ramo, estou ansiosos para aprender e crescer como desenvolvedor de jogos.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://maufreitas.github.io/MauFreitas.io/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
